# Storage contract for the KOSA materials data layer (dl_materials): the dataset
# plus the durable star-schema tables the scrape-external-data DAG's
# transform-load step upserts into. Mirrors the Bloomberg `securities` contract
# in bigquery.tf; the upsert SQL itself lives in the Airflow Python package.

variable "materials_bigquery_dataset_id" {
  description = "BigQuery dataset id for the KOSA materials star-schema mart."
  type        = string
  default     = "dl_materials"

  validation {
    condition     = can(regex("^[A-Za-z0-9_]+$", var.materials_bigquery_dataset_id))
    error_message = "materials_bigquery_dataset_id must contain only letters, digits, and underscores."
  }
}

locals {
  bigquery_tables_materials = {
    dim_datasources = {
      friendly_name   = "Materials datasources"
      table_role      = "dimension"
      description     = "Stable dimension of external materials datasources, for example the KOSA STEEL DATA portal."
      clustering      = []
      partition_field = null
      schema = [
        {
          name        = "id"
          type        = "STRING"
          mode        = "REQUIRED"
          description = "UUID generated by the BigQuery transform-load SQL only when inserting a new datasource."
        },
        {
          name        = "name"
          type        = "STRING"
          mode        = "REQUIRED"
          description = "Stable datasource name, for example kosa_steeldata."
        },
        {
          name        = "description"
          type        = "STRING"
          mode        = "NULLABLE"
          description = "Human-readable datasource description."
        },
      ]
    }

    dim_metrics = {
      friendly_name   = "Materials metrics"
      table_role      = "dimension"
      description     = "Stable dimension of curated materials metrics; joins dl_materials.dim_datasources on datasource_id."
      clustering      = []
      partition_field = null
      schema = [
        {
          name        = "id"
          type        = "STRING"
          mode        = "REQUIRED"
          description = "UUID generated by the BigQuery transform-load SQL only when inserting a new metric."
        },
        {
          name        = "datasource_id"
          type        = "STRING"
          mode        = "REQUIRED"
          description = "UUID reference to dl_materials.dim_datasources.id."
        },
        {
          name        = "name"
          type        = "STRING"
          mode        = "REQUIRED"
          description = "Curated metric name, for example steel_scrap_import_from_japan_volume."
        },
        {
          name        = "description"
          type        = "STRING"
          mode        = "NULLABLE"
          description = "Human-readable metric description."
        },
        {
          name        = "unit"
          type        = "STRING"
          mode        = "NULLABLE"
          description = "Metric unit, for example 천톤 or 천$."
        },
      ]
    }

    fact_metals = {
      friendly_name   = "Materials fact values"
      table_role      = "fact"
      description     = "KOSA-derived materials fact values upserted by Python/Airflow BigQuery SQL and partitioned by logical_date."
      clustering      = ["metric_id", "time_grain"]
      partition_field = "logical_date"
      schema = [
        {
          name        = "id"
          type        = "STRING"
          mode        = "REQUIRED"
          description = "UUID generated by the BigQuery transform-load SQL only when inserting a new fact."
        },
        {
          name        = "metric_id"
          type        = "STRING"
          mode        = "REQUIRED"
          description = "UUID reference to dl_materials.dim_metrics.id."
        },
        {
          name        = "logical_date"
          type        = "DATE"
          mode        = "REQUIRED"
          description = "Observation month start derived from the source 시점 column (current or previous-year split)."
        },
        {
          name        = "time_grain"
          type        = "STRING"
          mode        = "REQUIRED"
          description = "Time grain of the fact row, M for monthly KOSA series."
        },
        {
          name        = "metric_value"
          type        = "NUMERIC"
          mode        = "REQUIRED"
          description = "Numeric metric value parsed from the source cell (thousands separators stripped)."
        },
        {
          name        = "ingested_at"
          type        = "TIMESTAMP"
          mode        = "REQUIRED"
          description = "Timestamp when the BigQuery transform-load SQL upserted the row."
        },
      ]
    }
  }
}

resource "google_bigquery_dataset" "materials" {
  project    = var.project_id
  dataset_id = var.materials_bigquery_dataset_id
  location   = var.location

  friendly_name = "Materials data layer"
  description   = "Dataset for KOSA materials star-schema dimensions and fact values managed by the scrape-external-data transform-load step."

  delete_contents_on_destroy = var.bigquery_dataset_delete_contents_on_destroy
  deletion_policy            = var.bigquery_dataset_deletion_policy

  labels = merge(local.common_labels, {
    data_layer = "materials"
  })

  depends_on = [
    google_project_service.required["bigquery.googleapis.com"],
  ]
}

resource "google_bigquery_table" "materials" {
  for_each = local.bigquery_tables_materials

  project    = var.project_id
  dataset_id = google_bigquery_dataset.materials.dataset_id
  table_id   = each.key

  friendly_name = each.value.friendly_name
  description   = each.value.description

  schema = jsonencode(each.value.schema)

  clustering               = length(each.value.clustering) > 0 ? each.value.clustering : null
  deletion_protection      = var.bigquery_table_deletion_protection
  require_partition_filter = each.value.partition_field != null

  labels = merge(local.common_labels, {
    data_layer = "materials"
    table_role = each.value.table_role
  })

  dynamic "time_partitioning" {
    for_each = each.value.partition_field == null ? [] : [each.value.partition_field]

    content {
      type  = "DAY"
      field = time_partitioning.value
    }
  }
}

# Table access is dataset-scoped (project-level jobUser is granted once in
# bigquery_transform.tf and covers every dataset). The transform-load MERGEs the
# materials tables, so the transformer SA needs dataEditor on this dataset too.
resource "google_bigquery_dataset_iam_member" "bigquery_transformer_materials_dataset_editor" {
  project    = var.project_id
  dataset_id = google_bigquery_dataset.materials.dataset_id
  role       = "roles/bigquery.dataEditor"
  member     = "serviceAccount:${google_service_account.bigquery_transformer.email}"
}

output "bigquery_materials_dataset" {
  description = "BigQuery dataset configured for the KOSA materials star schema."
  value = {
    project    = google_bigquery_dataset.materials.project
    dataset_id = google_bigquery_dataset.materials.dataset_id
    id         = google_bigquery_dataset.materials.id
    location   = google_bigquery_dataset.materials.location
  }
}

output "bigquery_materials_tables" {
  description = "Materials star-schema tables keyed by table id."
  value = {
    for key, table in google_bigquery_table.materials :
    key => {
      dataset_id = table.dataset_id
      table_id   = table.table_id
      full_name  = "${table.project}.${table.dataset_id}.${table.table_id}"
    }
  }
}
