locals {
  # APIs required by the current GCS, BigQuery, and Airflow transform-load lesson surface.
  # serviceusage must be enabled for Terraform to manage other APIs. Add per
  # phase as resources grow.
  required_project_services = toset([
    "bigquery.googleapis.com",
    "iam.googleapis.com",
    "serviceusage.googleapis.com",
    "storage.googleapis.com",
  ])

  common_labels = merge(
    {
      study_workspace = "terraform_basics"
      study_track     = "gcp_provider_practice"
      study_session   = "airflow_cloud_run_bigquery_etl"
      environment     = var.environment
      owner           = var.owner
      managed_by      = "terraform"
    },
    var.extra_labels
  )

  # Derive the concrete bucket name for each logical role.
  buckets = {
    for key, cfg in var.buckets :
    key => merge(cfg, {
      name = "${var.project_id}-${var.environment}-${cfg.name_suffix}"
    })
  }

  raw_object_prefix = trim(var.raw_object_prefix, "/")

  # By default, grant the Airflow GCS service account a custom role that can
  # create/read/update objects and replace object contents at the same key. GCS
  # replacement uploads require storage.objects.delete; set
  # airflow_gcs_allow_object_replacement=false only when keys are always unique.
  airflow_gcs_uses_custom_cru_role = var.airflow_gcs_bucket_role == null
  airflow_gcs_bucket_role          = local.airflow_gcs_uses_custom_cru_role ? google_project_iam_custom_role.airflow_gcs_object_cru[0].name : var.airflow_gcs_bucket_role
  airflow_gcs_custom_cru_permissions = toset([
    "storage.multipartUploads.abort",
    "storage.multipartUploads.create",
    "storage.multipartUploads.listParts",
    "storage.objects.create",
    "storage.objects.createContext",
    "storage.objects.get",
    "storage.objects.list",
    "storage.objects.update",
    "storage.objects.updateContext",
  ])
  airflow_gcs_custom_role_permissions = var.airflow_gcs_allow_object_replacement ? setunion(local.airflow_gcs_custom_cru_permissions, toset([
    "storage.objects.delete",
  ])) : local.airflow_gcs_custom_cru_permissions

  bigquery_tables_mongo_contract = {
    dim_grains = {
      friendly_name   = "Securities grains"
      table_role      = "dimension"
      description     = "Stable dimension of source Mongo Bloomberg grains used by the Python/Airflow transform-load workflow."
      clustering      = []
      partition_field = null
      schema = [
        {
          name        = "id"
          type        = "STRING"
          mode        = "REQUIRED"
          description = "Source Mongo datasetId."
        },
        {
          name        = "name"
          type        = "STRING"
          mode        = "REQUIRED"
          description = "Source Mongo grainId."
        },
        {
          name        = "description"
          type        = "STRING"
          mode        = "NULLABLE"
          description = "Source grain description when available."
        },
      ]
    }

    dim_metrics = {
      friendly_name   = "Securities metrics"
      table_role      = "dimension"
      description     = "Stable dimension of Mongo-derived Bloomberg metrics used by the Python/Airflow transform-load workflow."
      clustering      = []
      partition_field = null
      schema = [
        {
          name        = "id"
          type        = "STRING"
          mode        = "REQUIRED"
          description = "UUID generated by the BigQuery transform-load SQL only when inserting a new metric."
        },
        {
          name        = "grain_id"
          type        = "STRING"
          mode        = "REQUIRED"
          description = "Source Mongo datasetId matching dl_bloomberg_data.dim_grains.id."
        },
        {
          name        = "name"
          type        = "STRING"
          mode        = "REQUIRED"
          description = "Derived metric name, for example SX5E_Index_Open."
        },
        {
          name        = "description"
          type        = "STRING"
          mode        = "NULLABLE"
          description = "Derived metric description when available."
        },
      ]
    }

    fact_values = {
      friendly_name   = "Bloomberg fact values"
      table_role      = "fact"
      description     = "Mongo-derived Bloomberg fact values upserted by Python/Airflow BigQuery SQL and partitioned by logical_date."
      clustering      = ["grain_id", "metric_id", "time_grain"]
      partition_field = "logical_date"
      schema = [
        {
          name        = "id"
          type        = "STRING"
          mode        = "REQUIRED"
          description = "UUID generated by the BigQuery transform-load SQL only when inserting a new fact."
        },
        {
          name        = "sample_id"
          type        = "STRING"
          mode        = "REQUIRED"
          description = "Source Mongo _id."
        },
        {
          name        = "grain_id"
          type        = "STRING"
          mode        = "REQUIRED"
          description = "Source Mongo datasetId matching dl_bloomberg_data.dim_grains.id."
        },
        {
          name        = "grain_name"
          type        = "STRING"
          mode        = "REQUIRED"
          description = "Source Mongo grainId."
        },
        {
          name        = "logical_date"
          type        = "DATE"
          mode        = "REQUIRED"
          description = "Source data.dt date or date derived from the raw GCS object path."
        },
        {
          name        = "time_grain"
          type        = "STRING"
          mode        = "REQUIRED"
          description = "Time grain of the fact row, D for daily samples."
        },
        {
          name        = "metric_id"
          type        = "STRING"
          mode        = "REQUIRED"
          description = "UUID reference to dl_bloomberg_data.dim_metrics.id."
        },
        {
          name        = "metric_value"
          type        = "STRING"
          mode        = "REQUIRED"
          description = "Metric value preserved as a string from the source sample."
        },
        {
          name        = "updated_at"
          type        = "TIMESTAMP"
          mode        = "REQUIRED"
          description = "Source updatedAt timestamp."
        },
        {
          name        = "ingested_at"
          type        = "TIMESTAMP"
          mode        = "REQUIRED"
          description = "Timestamp when the BigQuery transform-load SQL upserted the row."
        },
      ]
    }
  }

  # Safety confirmations surfaced as an output for plan review.
  safety_contract = {
    billing_budget_confirmed            = var.billing_budget_confirmed
    adc_credentials_reviewed            = var.adc_credentials_reviewed
    remote_state_reviewed               = var.remote_state_reviewed
    manages_only_gcs_buckets            = false
    manages_bigquery_dataset            = true
    manages_bigquery_stable_tables      = true
    manages_airflow_gcs_identity        = true
    manages_airflow_orchestrator        = true
    manages_bigquery_transform_identity = true
    bigquery_table_schema_contract      = var.bigquery_table_schema_contract
    airflow_gcs_uses_custom_cru_role    = local.airflow_gcs_uses_custom_cru_role
    airflow_gcs_delete_permission       = (local.airflow_gcs_uses_custom_cru_role && var.airflow_gcs_allow_object_replacement) || local.airflow_gcs_bucket_role == "roles/storage.objectUser" || local.airflow_gcs_bucket_role == "roles/storage.objectAdmin"
    creates_airflow_service_account_key = var.create_airflow_service_account_key
  }
}
